import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "@/styles/layout.module.css";
import Link from "next/link";

const geistSans = Geist({ subsets: ["latin"], variable: "--font-sans" });
const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-mono" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.container}>
          <header className={styles.header}>
            <nav className={styles.navbar}>
              <Link href="/" className={styles.navBut}>Home</Link>
              <Link href="/irac" className={styles.navBut}>IRAC</Link>
              <Link href="/referencing" className={styles.navBut}>Referencing Guide</Link>
              <Link href="/legalTerms" className={styles.navBut}>Legal Terms</Link>
              <Link href="/caseLaw" className={styles.navBut}>Case Law</Link>
              <Link href="/branchesOfLaw" className={styles.navBut}>Branches Of Law</Link>
              <Link href="/legalWriting" className={styles.navBut}>Legal Writing Help</Link>
              <Link href="/improveWriting" className={styles.navBut}>Improve Writing</Link>
              <Link href="/plannedFeatures" className={styles.navBut}>Planned Features</Link>
              <Link href="/culpability" className={styles.navBut}>Culpability</Link>
              <Link href="/criminalLawGuide" className={styles.navBut}>Criminal Law</Link>
            </nav>
            <div className={styles.sideBar}>

            </div>
          </header>

          <main className={styles.mainContent}>
            {children}
          </main>

          <footer className={styles.footer}>
            <p>© 2025 Your App Name. All rights reserved.</p>
          </footer>
        </div>
      </body>
    </html>
  );
}

